### ISSUE TITLE
Does not fetch client config

### ISSUE THREAD

**Issue by rheimus** [minakitty/ServerSync-Updater#3]
Currently does not fetch the client config for serversync.

Ends up with SS trying to connect to localhost.

Only an issue if the user has never set up the client config for SS.

**Comment by raindropworks** [comment]
Yeah ... that was something you noted in #1 and fixed already.  In my production version, I shipped winhttpjs.bat, update.bat, and the serversync-client.cfg file in it's proper spot with the default config pre-patched.  My instructions weren't necessarily the clearest, admittedly I wasn't feeling the best at the time yesterday

**Comment by raindropworks** [comment]
A bit of a necro, but the new version that I made today allows for a basic client config to be stored on the webserver with the current version of serversync, and the script will download it if it can't find a config file.  If it can't download, it'll give an error asking the user to talk to the modpack manager, since it's likely an error on their end.
